name: wrong8007 build routine

on:
  push:
    branches: [ master ]
    paths:
      - "core.c"
      - "include/**"
      - "trigger/**"
  pull_request:
    paths:
      - "core.c"
      - "include/**"
      - "trigger/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install kernel headers & build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential linux-headers-$(uname -r)

      - name: compile wrong8007
        run: make
