name: wrong8007 nightly build routine

on:
  schedule:
    - cron: "0 2 * * *"  # 2 AM UTC
  workflow_dispatch:     # on-demand trigger

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel: ["5.4.0-146-generic", "5.10.0-25-generic", "6.1.0-26-generic", "6.6.0-14-generic"]
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install kernel headers & build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential linux-headers-${{ matrix.kernel }} || true

      - name: compile wrong8007
        run: |
          make clean
          make KERNEL_VERSION=${{ matrix.kernel }} test || exit 1
