name: wrong8007 nightly build routine

on:
  schedule:
    - cron: "0 2 * * *"  # nightly at 2 AM UTC
  workflow_dispatch:     # on-demand trigger

jobs:
  build:
    name: build on kernel ${{ matrix.kernel.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel:
          - version: "5.4.236"
            major: "5"
          - version: "5.10.210"
            major: "5"
          - version: "6.1.47"
            major: "6"
          - version: "6.6.14"
            major: "6"
    continue-on-error: true
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc flex bison libssl-dev wget tar libelf-dev

      - name: restore cached kernel sources
        uses: actions/cache@v3
        id: cache-kernel
        with:
          path: linux-${{ matrix.kernel.version }}
          key: kernel-${{ matrix.kernel.version }}

      - name: download and prepare kernel sources if not cached
        if: steps.cache-kernel.outputs.cache-hit != 'true'
        run: |
          echo "Downloading kernel ${{ matrix.kernel.version }} sources..."
          wget https://cdn.kernel.org/pub/linux/kernel/v${{ matrix.kernel.major }}.x/linux-${{ matrix.kernel.version }}.tar.gz
          tar -xzf linux-${{ matrix.kernel.version }}.tar.gz
          rm linux-${{ matrix.kernel.version }}.tar.gz
          cd linux-${{ matrix.kernel.version }}
          make defconfig
          make modules_prepare

      - name: compile wrong8007
        run: |
          KBUILD_MODPOST_WARN=1 make -C linux-${{ matrix.kernel.version }} M=$GITHUB_WORKSPACE modules V=1 || { echo "Build failed for kernel ${{ matrix.kernel.version }}"; exit 1; }
